version: '2'
services:

  proxy:
    build:
      context:  ./envoy
      dockerfile: Dockerfile.proxy
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy.yaml
      - ./envoy/envoy_wasm.wasm:/etc/envoy_wasm.wasm
      # Uncomment this line if you want to use your own Envoy with WASM enabled.
  #    - ./envoy/istio/envoy:/usr/local/bin/envoy
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "18000:80"
      - "18001:8001"

  web_service:
    image: hashicorp/http-echo
    command:
      - '-text="You just ran wasm module within Istio/Envoy"'
    networks:
      envoymesh:
        aliases:
          - web_service
    expose:
      - "5678"
    ports:
      - "18080:5678"

networks:
  envoymesh: {}
